modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/Magistu/Epic-Knights/issues"
displayURL="https://github.com/Magistu/Epic-Knights"
license = "All Right Reserved"
[[mods]]
modId = "magistuarmory"
version = "${version}"
displayName = "Epic Knights Mod"
authors = "Magistu"
credits = ["StaxiHD", "Mino", "Lexiolty", "Jackiecrazy", "CrazyBarkley", "Ryuje", "Cole3050", "taizazanek"]
description = '''
Adds medieval stuff to the game
'''

[[dependencies.magistuarmory]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.magistuarmory]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.magistuarmory]]
modId = "architectury"
mandatory = true
versionRange = "[8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.magistuarmory]]
modId = "cloth_config"
mandatory = true
versionRange = "[10,)"
ordering = "AFTER"
side = "BOTH"