import groovy.json.JsonOutput

plugins {
    id "com.github.johnrengelman.shadow" version "7.0.0"
    id "com.hypherionmc.modutils.modpublisher" version "2.1.7"
}

version = rootProject.mod_version
archivesBaseName = "epic-knights-${rootProject.display_minecraft_version}-fabric"

loom {
}

architectury {
    platformSetupLoomIde()
    fabric()
}

configurations {
    common
    shadowCommon // Don't use shadow from the shadow plugin because we don't want IDEA to index this.
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    modApi "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"
    modApi "dev.architectury:architectury-fabric:${rootProject.architectury_api_version}"
    modImplementation "me.shedaniel.cloth:cloth-config-fabric:${rootProject.cloth_config_version}"
    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionFabric")) { transitive false }
    modImplementation "maven.modrinth:modmenu:${rootProject.modmenu_version}-fabric"
}

repositories {
    maven { url "https://maven.terraformersmc.com/releases/" }
}

processResources {
    def rawAuthors      = project.mod_authors.toString()
    def rawContributors = project.mod_contributors.toString()

    def authorsList      = rawAuthors.split(",")*.trim().findAll { it }
    def contributorsList = rawContributors.split(",")*.trim().findAll { it }

    def authorsArray      = JsonOutput.toJson(authorsList)
    def contributorsArray = JsonOutput.toJson(contributorsList)

    def expandProps = [
            "mod_id"                    : project.mod_id,
            "mod_name"                  : project.mod_display_name,
            "mod_version"               : project.mod_version,
            "mod_description"           : project.mod_description,
            "mod_authors"               : authorsArray,
            "mod_contributors"          : contributorsArray,
            "mod_license"               : project.mod_license,
            "mod_discord_url"           : project.mod_discord_url,
            "mod_git_url"               : project.mod_git_url,
            "mod_issues_url"            : project.mod_issues_url,
            "mod_page_url"              : project.mod_page_url,
            "minecraft_min_version"     : project.minecraft_min_version,
            "minecraft_max_version"     : project.minecraft_max_version,
            "fabric_loader_version"     : project.fabric_loader_version,
            "min_fabric_loader_version" : project.min_fabric_loader_version,
            "architectury_api_version"  : project.architectury_api_version,
            "cloth_config_version"      : project.cloth_config_version,
            "epic_knights_version"      : project.epic_knights_version,
    ]

    inputs.properties(expandProps)

    filesMatching('fabric.mod.json') {
        expand(expandProps)
    }
}

shadowJar {
    exclude "architectury.common.json"

    configurations = [project.configurations.shadowCommon]
    archiveClassifier.set("dev-shadow")
}

remapJar {
    inputFile.set shadowJar.archiveFile
    dependsOn shadowJar
    archiveClassifier.set(null)
}

jar {
    archiveClassifier.set("dev")
}

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}

publisher {
    def mcVersionsNeo = (rootProject.ext.minecraftGameVersions as List).collect { it.toString() } as String[]
    def changelogFile = rootProject.file("fabric/CHANGELOG.md")
    def changelogText = changelogFile.exists() ? changelogFile.getText("UTF-8") : ""

    apiKeys {
        modrinth System.getenv("MODRINTH_TOKEN")
        curseforge System.getenv("CURSEFORGE_TOKEN")
    }

    setCurseID((rootProject.findProperty("mod_curseforge_id") ?: "").toString())

    setModrinthID((rootProject.findProperty("mod_modrinth_id") ?: "").toString())

    setVersionType((rootProject.findProperty("release_channel") ?: "release").toString())

    setChangelog(changelogText)

    setVersion(rootProject.mod_version)

    setDisplayName("[${rootProject.display_minecraft_version}-fabric]-${rootProject.mod_display_name}-${rootProject.mod_version}")

    setGameVersions(*mcVersionsNeo)

    setLoaders("fabric")

    setCurseEnvironment("both")

    setArtifact(tasks.remapJar)

    modrinthDepends {
        required("cloth-config")
        required("architectury-api")
    }

    curseDepends {
        required("cloth-config")
        required("architectury-api")
    }
}
