# Project
maven_group                     = io.github.magistu
release_channel                 = release

# Common
minecraft_version               = 1.20.1
display_minecraft_version       = 1.20.1
minecraft_min_version           = 1.20
minecraft_max_version           = 1.20.2
enabled_platforms               = fabric,forge
parchment_mappings              = 2024.11.07

# Fabric
fabric_loader_version           = 0.14.21
min_fabric_loader_version       = 0.14
fabric_api_version              = 0.84.0+1.20.1

# Forge
forge_version                   = 47.4.0
forge_version_range             = [47,)
forge_loader_version_range      = [2,)

# Mod options
mod_version                     = 10.11
mod_id                          = magistuarmory
mod_display_name                = Epic-Knights: Shields, Armor and Weapons
mod_authors                     = Magistu
mod_contributors                = StaxiHD, Mino, Lexiolty, Jackiecrazy, CrazyBarkley, Ryuje, Witchkings, Cole3050, taizazanek, thyreo
mod_description                 = Adds medieval stuff to the game
mod_license                     = All Rights Reserved
mod_page_url                    = https://www.curseforge.com/minecraft/mc-mods/epic-knights-armor-and-weapons
mod_issues_url                  = https://github.com/Magistu/Epic-Knights/issues
mod_git_url                     = https://github.com/Magistu/Epic-Knights
mod_discord_url                 = https://discord.gg/H9CVcXEmYe
mod_curseforge_id               = 509041
mod_modrinth_id                 = L6jvzao4

# Dependencies
architectury_api_version        = 9.0.8
cloth_config_version            = 11.0.99
epic_knights_version            = 9.26
modmenu_version                 = 7.1.0
epic_fight_version              = 20.13.6

# Gradle
org.gradle.jvmargs              = -Xmx4G
org.gradle.parallel             = true


