# Project
maven_group                     = io.github.magistu
release_channel                 = release

# Common
minecraft_version               = 26.1.2
display_minecraft_version       = 26.1.2
minecraft_min_version           = 26.1.2
minecraft_max_version           = 26.1.3
enabled_platforms               = fabric,neoforge

# Fabric
fabric_loader_version           = 0.19.5
min_fabric_loader_version       = 0.19.5
fabric_api_version              = 0.155.3+26.1.2

# NeoForge
neoforge_version                = 26.1.2.109
neoforge_version_range          = [26.1.2.109,)
neoforge_loader_version_range   = [4,)

# Mod options
mod_version                     = 10.12
mod_id                          = magistuarmory
mod_display_name                = Epic Knights: Shields, Armor and Weapons
mod_authors                     = Magistu
mod_contributors                = StaxiHD, Mino, Lexiolty, Jackiecrazy, CrazyBarkley, Ryuje, Witchkings, Cole3050, taizazanek, thyreo
mod_description                 = Adds medieval stuff to the game
mod_license                     = All Rights Reserved
mod_page_url                    = https://www.curseforge.com/minecraft/mc-mods/epic-knights-armor-and-weapons
mod_issues_url                  = https://github.com/Magistu/Epic-Knights/issues
mod_git_url                     = https://github.com/Magistu/Epic-Knights
mod_discord_url                 = https://discord.gg/H9CVcXEmYe
mod_curseforge_id               = 509041
mod_modrinth_id                 = L6jvzao4

# Dependencies
architectury_api_version        = 20.1.14
cloth_config_version            = 26.1.154
epic_knights_version             = 10.2
modmenu_version                 = 18.0.1
epic_fight_version              = ???

# Gradle
org.gradle.jvmargs              = -Xmx4G
org.gradle.parallel             = true