org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

minecraft_version=1.21
minecraft_version_range=[1.21,1.21.1.1)
minecraft_version_condition==1.21
enabled_platforms=fabric,neoforge
parchment_mappings=2024.05.01

archives_base_name=[1.21]-Epic-Knights
mod_version=9.25
maven_group=io.github.magistu

architectury_version=13.0.6
cloth_config_version=15.0.128

fabric_loader_version=0.15.11
fabric_api_version=0.100.1+1.21

neoforge_version=21.0.110-beta
neoforge_version_range=[21,)
loader_version_range=[4,)
modmenu_version=11.0.1

mod_id=magistuarmory
mod_name=Epic Knights: Shields, Armor and Weapons
mod_license=All Rights Reserved
mod_group_id=io.github.magistu
mod_authors=Magistu
mod_credits=StaxiHD, Mino, Lexiolty, Jackiecrazy, CrazyBarkley, Ryuje, Witchkings, Cole3050, taizazanek
mod_description=Adds medieval stuff to the game
mod_issues_url=https://github.com/Magistu/Epic-Knights/issues
mod_sources_url=https://github.com/Magistu/Epic-Knights
mod_home_url=https://www.curseforge.com/minecraft/mc-mods/Epic-Knights
mod_update_json=https://raw.githubusercontent.com/Magistu/UpdateJSONs/master/magistuarmory.json
