blank_issues_enabled: false
contact_links:
  - name: Official Discord Server
    url: https://discord.gg/3hNZtqjgRs
    about: If you are experiencing issues with Epic Knights mod, go to our support in our Discord server.
