import groovy.json.JsonOutput

plugins {
    id "com.github.johnrengelman.shadow" version "7.0.0"
    id "com.hypherionmc.modutils.modpublisher" version "2.1.7"
}

architectury {
    platformSetupLoomIde()
    forge()
}

version = rootProject.mod_version
archivesBaseName = "epic-knights-${rootProject.display_minecraft_version}-forge"

loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath

    forge {
        convertAccessWideners.set(true)
    }
}

configurations {
    common
    shadowCommon // Don't use shadow from the shadow plugin because we don't want IDEA to index this.
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentForge.extendsFrom common
}

dependencies {
    forge "net.minecraftforge:forge:${rootProject.minecraft_version}-${rootProject.forge_version}"
    modApi "dev.architectury:architectury-forge:${rootProject.architectury_api_version}"
    modApi "me.shedaniel.cloth:cloth-config-forge:${rootProject.cloth_config_version}"
    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionForge")) { transitive = false }
}

processResources {
    def authors      = project.mod_authors.toString().split(",")*.trim().findAll{it}.join(", ")
    def contributors = project.mod_contributors.toString().split(",")*.trim().findAll{it}.join(", ")

    def expandProps = [
            "mod_id"                        : project.mod_id,
            "mod_name"                      : project.mod_display_name,
            "mod_version"                   : project.mod_version,
            "mod_description"               : project.mod_description,
            "mod_authors"                   : authors,
            "mod_contributors"              : contributors,
            "mod_license"                   : project.mod_license,
            "mod_discord_url"               : project.mod_discord_url,
            "mod_git_url"                   : project.mod_git_url,
            "mod_issues_url"                : project.mod_issues_url,
            "mod_page_url"                  : project.mod_page_url,
            "minecraft_min_version"         : project.minecraft_min_version,
            "minecraft_max_version"         : project.minecraft_max_version,
            "forge_version_range"           : project.forge_version_range,
            "forge_loader_version_range"    : project.forge_loader_version_range,
            "architectury_api_version"      : project.architectury_api_version,
            "cloth_config_version"          : project.cloth_config_version,
            "epic_knights_version"          : project.epic_knights_version,
    ]

    inputs.properties(expandProps)

    filesMatching('META-INF/mods.toml') {
        expand(expandProps)
    }
}

shadowJar {
    configurations = [project.configurations.shadowCommon]
    archiveClassifier.set("dev-shadow")
}

remapJar {
    inputFile.set shadowJar.archiveFile
    dependsOn shadowJar
    archiveClassifier.set(null)
}

jar {
    archiveClassifier.set("dev")
}

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}

publisher {
    def mcVersionsForge = (rootProject.ext.minecraftGameVersions as List).collect { it.toString() } as String[]
    def changelogFile = rootProject.file("forge/CHANGELOG.md")
    def changelogText = changelogFile.exists() ? changelogFile.getText("UTF-8") : ""

    apiKeys {
        modrinth System.getenv("MODRINTH_TOKEN")
        curseforge System.getenv("CURSEFORGE_TOKEN")
    }

    setCurseID((rootProject.findProperty("mod_curseforge_id") ?: "").toString())

    setModrinthID((rootProject.findProperty("mod_modrinth_id") ?: "").toString())

    setVersionType((rootProject.findProperty("release_channel") ?: "release").toString())

    setChangelog(changelogText)

    setVersion(rootProject.mod_version)

    setDisplayName("[${rootProject.display_minecraft_version}-forge]-${rootProject.mod_display_name}-${rootProject.mod_version}")

    setGameVersions(*mcVersionsForge)

    setLoaders("forge")

    setCurseEnvironment("both")

    setArtifact(tasks.remapJar)

    modrinthDepends {
        required("cloth-config")
        required("architectury-api")
    }

    curseDepends {
        required("cloth-config")
        required("architectury-api")
    }
}
