package com.magistuarmory.misc;

import java.util.HashSet;
import java.util.Set;

public class HeraldryRegistry
{
    static Set<String> HERALDRY = new HashSet<>(Set.of(
            "amphithere",
            "base",
            "bird",
            "border",
            "bricks",
            "circle",
            "creeper",
            "cross",
            "curly_border",
            "diagonal_left",
            "diagonal_right",
            "diagonal_up_left",
            "diagonal_up_right",
            "dread",
            "eye",
            "fae",
            "feather",
            "fire",
            "fire_head",
            "flower",
            "globe",
            "gorgon",
            "gradient",
            "gradient_up",
            "half_horizontal",
            "half_horizontal_bottom",
            "half_vertical",
            "half_vertical_right",
            "hippocampus",
            "hippogryph_head",
            "ice",
            "ice_head",
            "lighting",
            "lighting_head",
            "mermaid",
            "mojang",
            "piglin",
            "rhombus",
            "sea_serpent",
            "skull",
            "small_stripes",
            "square_bottom_left",
            "square_bottom_right",
            "square_top_left",
            "square_top_right",
            "straight_cross",
            "stripe_bottom",
            "stripe_center",
            "stripe_downleft",
            "stripe_downright",
            "stripe_left",
            "stripe_middle",
            "stripe_right",
            "stripe_top",
            "triangles_bottom",
            "triangles_top",
            "triangle_bottom",
            "triangle_top",
            "troll",
            "unicorn",
            "weezer",
            "apostolic_cross",
            "bowl",
            "bull",
            "chess",
            "crusader_cross",
            "dragon",
            "eagle",
            "horse",
            "lily",
            "lion1",
            "lion2",
            "orthodox_cross",
            "snake",
            "sun",
            "swords",
            "tower",
            "tree",
            "two_headed_eagle"));
    
    public static void register(String name) {
        HERALDRY.add(name);
    }
    
    public static boolean isRegistered(String name) {
        return HERALDRY.contains(name);
    }
}
