plugins {
    id "java-library"
}

archivesBaseName = "epic-knights-${rootProject.display_minecraft_version}"

dependencies {
    // We depend on fabric loader here to use the fabric @Environment annotations and get the mixin dependencies
    // Do NOT use other classes from fabric loader
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    // Remove the next line if you don't want to depend on the API
    modApi "dev.architectury:architectury:${rootProject.architectury_api_version}"

    compileOnly "fuzs.forgeconfigapiport:forgeconfigapiport-common:$forge_config_api_version"
    implementation 'com.moandjiezana.toml:toml4j:0.7.2'
}

architectury {
    common(rootProject.enabled_platforms.split(","))
}
