plugins {
    id "java-library"
}

architectury {
    common rootProject.enabled_platforms.split(',')
}

loom {
}

dependencies {
    compileOnly "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"
    compileOnly "dev.architectury:architectury:$rootProject.architectury_api_version"
    compileOnly "me.shedaniel.cloth:cloth-config:$rootProject.cloth_config_version"
}