package com.magistuarmory.item.armor;

import com.magistuarmory.EpicKnights;
import com.magistuarmory.config.ArmorConfig;
import dev.architectury.registry.registries.DeferredRegister;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.tags.TagKey;
import net.minecraft.world.item.ArmorMaterial;
import net.minecraft.world.item.crafting.Ingredient;

public class ArmorTypes
{
	public static final ArmorConfig ARMOR_CONFIG = EpicKnights.CONFIG.armor;

	public static DeferredRegister<ArmorMaterial> ARMOR_MATERIALS = DeferredRegister.create(EpicKnights.ID, Registries.ARMOR_MATERIAL);

	public static final ArmorType MINICROWN = new ArmorType(ARMOR_MATERIALS, ResourceLocation.fromNamespaceAndPath("magistuarmory", "minicrown"), ResourceLocation.parse("magistuarmory:minicrown"), ARMOR_CONFIG.minicrown.toughness, 0.0f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.minicrown.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.minicrown.helmetDefense }, 25, SoundEvents.ARMOR_EQUIP_GOLD, ARMOR_CONFIG.minicrown.enabled, false, "c:ingots/gold");

	public static final ArmorType CROWN = new ArmorType(ARMOR_MATERIALS, ResourceLocation.fromNamespaceAndPath("magistuarmory", "crown"), ResourceLocation.parse("magistuarmory:crown"), ARMOR_CONFIG.crown.toughness, 0.0f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.crown.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.crown.helmetDefense }, 25, SoundEvents.ARMOR_EQUIP_GOLD, ARMOR_CONFIG.crown.enabled, true, "c:ingots/gold");

	public static final ArmorType FLOWERCROWN = new ArmorType(ARMOR_MATERIALS, ResourceLocation.fromNamespaceAndPath("magistuarmory", "flowercrown"), ResourceLocation.parse("magistuarmory:flowercrown"), ARMOR_CONFIG.flowercrown.toughness, 0.0f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.flowercrown.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.flowercrown.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, ARMOR_CONFIG.flowercrown.enabled, true);

	public static final ArmorType KNIGHT = new ArmorType(ARMOR_MATERIALS, ResourceLocation.fromNamespaceAndPath("magistuarmory", "knight"), ResourceLocation.withDefaultNamespace("default"), ARMOR_CONFIG.knight.toughness, 0.5f, new Integer[] { ARMOR_CONFIG.knight.bootsDurability, ARMOR_CONFIG.knight.leggingsDurability, ARMOR_CONFIG.knight.chestplateDurability, 0 }, new Integer[] { ARMOR_CONFIG.knight.bootsDefense, ARMOR_CONFIG.knight.leggingsDefense, ARMOR_CONFIG.knight.chestplateDefense, 0 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.knight.enabled, false, "c:ingots/steel");

	public static final ArmorType ARMET = new ArmorType(ARMOR_MATERIALS, ResourceLocation.fromNamespaceAndPath("magistuarmory", "armet"), ResourceLocation.parse("magistuarmory:armet"), ARMOR_CONFIG.armet.toughness, 0.5f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.armet.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.armet.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.armet.enabled, true, "c:ingots/steel");

	public static final ArmorType STECHHELM = new ArmorType(ARMOR_MATERIALS, ResourceLocation.fromNamespaceAndPath("magistuarmory", "stechhelm"), ResourceLocation.parse("magistuarmory:stechhelm"), ARMOR_CONFIG.stechhelm.toughness, 1.5f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.stechhelm.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.stechhelm.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.stechhelm.enabled, false, "c:ingots/steel");

	public static final ArmorType JOUSTING = new ArmorType(ARMOR_MATERIALS, ResourceLocation.fromNamespaceAndPath("magistuarmory", "jousting"), ResourceLocation.withDefaultNamespace("default"), ARMOR_CONFIG.jousting.toughness, 1.5f, new Integer[] { ARMOR_CONFIG.jousting.bootsDurability, ARMOR_CONFIG.jousting.leggingsDurability, ARMOR_CONFIG.jousting.chestplateDurability, 0 }, new Integer[] { ARMOR_CONFIG.jousting.bootsDefense, ARMOR_CONFIG.jousting.leggingsDefense, ARMOR_CONFIG.jousting.chestplateDefense, 0 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.jousting.enabled, false, "c:ingots/steel");

	public static final ArmorType SALLET = new ArmorType(ARMOR_MATERIALS, ResourceLocation.fromNamespaceAndPath("magistuarmory", "sallet"), ResourceLocation.parse("magistuarmory:sallet"), ARMOR_CONFIG.sallet.toughness, 0.5f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.sallet.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.sallet.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.sallet.enabled, false, "c:ingots/steel");

	public static final ArmorType GOTHIC = new ArmorType(ARMOR_MATERIALS, ResourceLocation.fromNamespaceAndPath("magistuarmory", "gothic"), ResourceLocation.withDefaultNamespace("default"), ARMOR_CONFIG.gothic.toughness, 0.5f, new Integer[] { ARMOR_CONFIG.gothic.bootsDurability, ARMOR_CONFIG.gothic.leggingsDurability, ARMOR_CONFIG.gothic.chestplateDurability, 0 }, new Integer[] { ARMOR_CONFIG.gothic.bootsDefense, ARMOR_CONFIG.gothic.leggingsDefense, ARMOR_CONFIG.gothic.chestplateDefense, 0 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.gothic.enabled, false, "c:ingots/steel");

	public static final ArmorType MAXIMILIAN_HELMET = new ArmorType(ARMOR_MATERIALS, ResourceLocation.fromNamespaceAndPath("magistuarmory", "maximilian_helmet"), ResourceLocation.parse("magistuarmory:maximilian_helmet"), ARMOR_CONFIG.maximilianHelmet.toughness, 0.5f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.maximilianHelmet.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.maximilianHelmet.helmetDefense }, 12, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.maximilianHelmet.enabled, false, "c:ingots/steel");

	public static final ArmorType MAXIMILIAN = new ArmorType(ARMOR_MATERIALS, ResourceLocation.fromNamespaceAndPath("magistuarmory", "maximilian"), ResourceLocation.withDefaultNamespace("default"), ARMOR_CONFIG.maximilian.toughness, 0.5f, new Integer[] { ARMOR_CONFIG.maximilian.bootsDurability, ARMOR_CONFIG.maximilian.leggingsDurability, ARMOR_CONFIG.maximilian.chestplateDurability, 0 }, new Integer[] { ARMOR_CONFIG.maximilian.bootsDefense, ARMOR_CONFIG.maximilian.leggingsDefense, ARMOR_CONFIG.maximilian.chestplateDefense, 0 }, 12, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.maximilian.enabled, false, "c:ingots/steel");

	public static final ArmorType CHAINMAIL = new ArmorType(ARMOR_MATERIALS, ResourceLocation.fromNamespaceAndPath("magistuarmory", "chainmail"), ResourceLocation.withDefaultNamespace("default"), ARMOR_CONFIG.chainmail.toughness, 0.0f, new Integer[] { ARMOR_CONFIG.chainmail.bootsDurability, ARMOR_CONFIG.chainmail.leggingsDurability, ARMOR_CONFIG.chainmail.chestplateDurability, ARMOR_CONFIG.chainmail.helmetDurability }, new Integer[] { ARMOR_CONFIG.chainmail.bootsDefense, ARMOR_CONFIG.chainmail.leggingsDefense, ARMOR_CONFIG.chainmail.chestplateDefense, ARMOR_CONFIG.chainmail.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_CHAIN, ARMOR_CONFIG.chainmail.enabled, false, "c:ingots/steel");

	public static final ArmorType KETTLEHAT = new ArmorType(ARMOR_MATERIALS, ResourceLocation.fromNamespaceAndPath("magistuarmory", "kettlehat"), ResourceLocation.parse("magistuarmory:kettlehat"), ARMOR_CONFIG.kettlehat.toughness, 0.0f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.kettlehat.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.kettlehat.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_CHAIN, ARMOR_CONFIG.kettlehat.enabled, false, "c:ingots/steel");

	public static final ArmorType PLATEMAIL = new ArmorType(ARMOR_MATERIALS, ResourceLocation.fromNamespaceAndPath("magistuarmory", "platemail"), ResourceLocation.withDefaultNamespace("default"), ARMOR_CONFIG.platemail.toughness, 0.0f, new Integer[] { ARMOR_CONFIG.platemail.bootsDurability, ARMOR_CONFIG.platemail.leggingsDurability, ARMOR_CONFIG.platemail.chestplateDurability, 0 }, new Integer[] { ARMOR_CONFIG.platemail.bootsDefense, ARMOR_CONFIG.platemail.leggingsDefense, ARMOR_CONFIG.platemail.chestplateDefense, 0 }, 9, SoundEvents.ARMOR_EQUIP_CHAIN, ARMOR_CONFIG.platemail.enabled, false, "c:ingots/steel");

	public static final ArmorType BARBUTE = new ArmorType(ARMOR_MATERIALS, ResourceLocation.fromNamespaceAndPath("magistuarmory", "barbute"), ResourceLocation.parse("magistuarmory:barbute"), ARMOR_CONFIG.barbute.toughness, 0.0f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.barbute.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.barbute.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.barbute.enabled, false, "c:ingots/steel");

	public static final ArmorType HALFARMOR = new ArmorType(ARMOR_MATERIALS, ResourceLocation.fromNamespaceAndPath("magistuarmory", "halfarmor"), ResourceLocation.withDefaultNamespace("default"), ARMOR_CONFIG.halfarmor.toughness, 0.0f, new Integer[] { 0, 0, ARMOR_CONFIG.halfarmor.chestplateDurability, 0 }, new Integer[] { 0, 0, ARMOR_CONFIG.halfarmor.chestplateDefense, 0 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.halfarmor.enabled, false, "c:ingots/steel");

	public static final ArmorType CRUSADER = new ArmorType(ARMOR_MATERIALS, ResourceLocation.fromNamespaceAndPath("magistuarmory", "crusader"), ResourceLocation.parse("magistuarmory:crusader"), ARMOR_CONFIG.crusader.toughness, 0.0f, new Integer[] { ARMOR_CONFIG.crusader.bootsDurability, ARMOR_CONFIG.crusader.leggingsDurability, ARMOR_CONFIG.crusader.chestplateDurability, ARMOR_CONFIG.crusader.helmetDurability }, new Integer[] { ARMOR_CONFIG.crusader.bootsDefense, ARMOR_CONFIG.crusader.leggingsDefense, ARMOR_CONFIG.crusader.chestplateDefense, ARMOR_CONFIG.crusader.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_CHAIN, ARMOR_CONFIG.crusader.enabled, true, "c:ingots/steel");

	public static final ArmorType BRIGANDINE = new ArmorType(ARMOR_MATERIALS, ResourceLocation.fromNamespaceAndPath("magistuarmory", "brigandine"), ResourceLocation.withDefaultNamespace("default"), ARMOR_CONFIG.brigandine.toughness, 0.0f, new Integer[] { 0, 0, ARMOR_CONFIG.brigandine.chestplateDurability, 0 }, new Integer[] { 0, 0, ARMOR_CONFIG.brigandine.chestplateDefense, 0 }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, ARMOR_CONFIG.brigandine.enabled, true, "c:ingots/steel");

	public static final ArmorType GAMBESON = new ArmorType(ARMOR_MATERIALS, ResourceLocation.fromNamespaceAndPath("magistuarmory", "gambeson"), ResourceLocation.withDefaultNamespace("default"), ARMOR_CONFIG.gambeson.toughness, 0.0f, new Integer[] { ARMOR_CONFIG.gambeson.bootsDurability, ARMOR_CONFIG.gambeson.leggingsDurability, ARMOR_CONFIG.gambeson.chestplateDurability, ARMOR_CONFIG.gambeson.helmetDurability }, new Integer[] { ARMOR_CONFIG.gambeson.bootsDefense, ARMOR_CONFIG.gambeson.leggingsDefense, ARMOR_CONFIG.gambeson.chestplateDefense, ARMOR_CONFIG.gambeson.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, ARMOR_CONFIG.gambeson.enabled, true, () -> Ingredient.of(TagKey.create(Registries.ITEM, ResourceLocation.parse("magistuarmory:woolen_fabric"))));

	public static final ArmorType CEREMONIAL_ARMET = new ArmorType(ARMOR_MATERIALS, ResourceLocation.fromNamespaceAndPath("magistuarmory", "ceremonialarmet"), ResourceLocation.parse("magistuarmory:armet"), ARMOR_CONFIG.ceremonialArmet.toughness, 0.5f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.ceremonialArmet.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.ceremonialArmet.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.ceremonialArmet.enabled, false, "c:ingots/steel");

	public static final ArmorType CEREMONIAL = new ArmorType(ARMOR_MATERIALS, ResourceLocation.fromNamespaceAndPath("magistuarmory", "ceremonial"), ResourceLocation.withDefaultNamespace("default"), ARMOR_CONFIG.ceremonial.toughness, 0.5f, new Integer[] { ARMOR_CONFIG.ceremonial.bootsDurability, 0, ARMOR_CONFIG.ceremonial.chestplateDurability, 0 }, new Integer[] { ARMOR_CONFIG.ceremonial.bootsDefense, 0, ARMOR_CONFIG.ceremonial.chestplateDefense, 0 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.ceremonial.enabled, false, "c:ingots/steel");

	public static final ArmorType SHISHAK = new ArmorType(ARMOR_MATERIALS, ResourceLocation.fromNamespaceAndPath("magistuarmory", "shishak"), ResourceLocation.withDefaultNamespace("default"), ARMOR_CONFIG.shishak.toughness, 0.0f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.shishak.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.shishak.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.shishak.enabled, false, "c:ingots/steel");

	public static final ArmorType NORMAN = new ArmorType(ARMOR_MATERIALS, ResourceLocation.fromNamespaceAndPath("magistuarmory", "norman"), ResourceLocation.withDefaultNamespace("default"), ARMOR_CONFIG.norman.toughness, 0.0f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.norman.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.norman.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.norman.enabled, false, "c:ingots/steel");

	public static final ArmorType RUSTED_BARBUTE = new ArmorType(ARMOR_MATERIALS, ResourceLocation.fromNamespaceAndPath("magistuarmory", "rustedbarbute"), ResourceLocation.parse("magistuarmory:barbute"), ARMOR_CONFIG.rustedBarbute.toughness, 0.0f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.rustedBarbute.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.rustedBarbute.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.rustedBarbute.enabled, false, "c:ingots/steel");

	public static final ArmorType RUSTED_HALFARMOR = new ArmorType(ARMOR_MATERIALS, ResourceLocation.fromNamespaceAndPath("magistuarmory", "rustedhalfarmor"), ResourceLocation.withDefaultNamespace("default"), ARMOR_CONFIG.rustedHalfarmor.toughness, 0.0f, new Integer[] { 0, 0, ARMOR_CONFIG.rustedHalfarmor.chestplateDurability, 0 }, new Integer[] { 0, 0, ARMOR_CONFIG.rustedHalfarmor.chestplateDefense, 0 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.rustedHalfarmor.enabled, false, "c:ingots/steel");

	public static final ArmorType RUSTED_CHAINMAIL = new ArmorType(ARMOR_MATERIALS, ResourceLocation.fromNamespaceAndPath("magistuarmory", "rustedchainmail"), ResourceLocation.withDefaultNamespace("default"), ARMOR_CONFIG.rustedChainmail.toughness, 0.0f, new Integer[] { ARMOR_CONFIG.rustedChainmail.bootsDurability, ARMOR_CONFIG.rustedChainmail.leggingsDurability, ARMOR_CONFIG.rustedChainmail.chestplateDurability, ARMOR_CONFIG.rustedChainmail.helmetDurability }, new Integer[] { ARMOR_CONFIG.rustedChainmail.bootsDefense, ARMOR_CONFIG.rustedChainmail.leggingsDefense, ARMOR_CONFIG.rustedChainmail.chestplateDefense, ARMOR_CONFIG.rustedChainmail.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_CHAIN, ARMOR_CONFIG.rustedChainmail.enabled, false, "c:ingots/steel");

	public static final ArmorType RUSTED_KETTLEHAT = new ArmorType(ARMOR_MATERIALS, ResourceLocation.fromNamespaceAndPath("magistuarmory", "rustedkettlehat"), ResourceLocation.parse("magistuarmory:kettlehat"), ARMOR_CONFIG.rustedKettlehat.toughness, 0.0f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.rustedKettlehat.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.rustedKettlehat.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_CHAIN, ARMOR_CONFIG.rustedKettlehat.enabled, false, "c:ingots/steel");

	public static final ArmorType RUSTED_NORMAN = new ArmorType(ARMOR_MATERIALS, ResourceLocation.fromNamespaceAndPath("magistuarmory", "rustednorman"), ResourceLocation.withDefaultNamespace("default"), ARMOR_CONFIG.rustedNorman.toughness, 0.0f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.rustedNorman.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.rustedNorman.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_CHAIN, ARMOR_CONFIG.rustedNorman.enabled, false, "c:ingots/steel");

	public static final ArmorType RUSTED_CRUSADER = new ArmorType(ARMOR_MATERIALS, ResourceLocation.fromNamespaceAndPath("magistuarmory", "rustedcrusader"), ResourceLocation.parse("magistuarmory:crusader"), ARMOR_CONFIG.rustedCrusader.toughness, 0.0f, new Integer[] { ARMOR_CONFIG.rustedCrusader.bootsDurability, 0, ARMOR_CONFIG.rustedCrusader.chestplateDurability, ARMOR_CONFIG.rustedCrusader.helmetDurability }, new Integer[] { ARMOR_CONFIG.rustedCrusader.bootsDefense, 0, ARMOR_CONFIG.rustedCrusader.chestplateDefense, ARMOR_CONFIG.rustedCrusader.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_CHAIN, ARMOR_CONFIG.rustedCrusader.enabled, false, "c:ingots/steel");

	public static final ArmorType BASCINET = new ArmorType(ARMOR_MATERIALS, ResourceLocation.fromNamespaceAndPath("magistuarmory", "bascinet"), ResourceLocation.parse("magistuarmory:bascinet"), ARMOR_CONFIG.bascinet.toughness, 0.0f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.bascinet.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.bascinet.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.bascinet.enabled, false, "c:ingots/steel");

	public static final ArmorType XIV_CENTURY_KNIGHT = new ArmorType(ARMOR_MATERIALS, ResourceLocation.fromNamespaceAndPath("magistuarmory", "xivcenturyknight"), ResourceLocation.withDefaultNamespace("default"), ARMOR_CONFIG.xivCenturyKnight.toughness, 0.0f, new Integer[] { ARMOR_CONFIG.xivCenturyKnight.bootsDurability, ARMOR_CONFIG.xivCenturyKnight.leggingsDurability, ARMOR_CONFIG.xivCenturyKnight.chestplateDurability, 0 }, new Integer[] { ARMOR_CONFIG.xivCenturyKnight.bootsDefense, ARMOR_CONFIG.xivCenturyKnight.leggingsDefense, ARMOR_CONFIG.xivCenturyKnight.chestplateDefense, 0 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.xivCenturyKnight.enabled, false, "c:ingots/steel");

	public static final ArmorType WINGED_HUSSAR_CHESTPLATE = new ArmorType(ARMOR_MATERIALS, ResourceLocation.fromNamespaceAndPath("magistuarmory", "wingedhussarchestplate"), ResourceLocation.parse("magistuarmory:wingedhussarchestplate"), ARMOR_CONFIG.wingedHussarChestplate.toughness, 0.0f, new Integer[] { 0, 0, ARMOR_CONFIG.wingedHussarChestplate.chestplateDurability, 0 }, new Integer[] { 0, 0, ARMOR_CONFIG.wingedHussarChestplate.chestplateDefense, 0 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.wingedHussarChestplate.enabled, false, "c:ingots/steel");

	public static final ArmorType CUIRASSIER = new ArmorType(ARMOR_MATERIALS, ResourceLocation.fromNamespaceAndPath("magistuarmory", "cuirassier"), ResourceLocation.withDefaultNamespace("default"), ARMOR_CONFIG.cuirassier.toughness, 0.0f, new Integer[] { ARMOR_CONFIG.cuirassier.bootsDurability, ARMOR_CONFIG.cuirassier.leggingsDurability, ARMOR_CONFIG.cuirassier.chestplateDurability, ARMOR_CONFIG.cuirassier.helmetDurability }, new Integer[] { ARMOR_CONFIG.cuirassier.bootsDefense, ARMOR_CONFIG.cuirassier.leggingsDefense, ARMOR_CONFIG.cuirassier.chestplateDefense, ARMOR_CONFIG.cuirassier.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.cuirassier.enabled, true, "c:ingots/steel");

	public static final ArmorType KASTENBRUST = new ArmorType(ARMOR_MATERIALS, ResourceLocation.fromNamespaceAndPath("magistuarmory", "kastenbrust"), ResourceLocation.withDefaultNamespace("default"), ARMOR_CONFIG.kastenbrust.toughness, 0.5f, new Integer[] { ARMOR_CONFIG.kastenbrust.bootsDurability, ARMOR_CONFIG.kastenbrust.leggingsDurability, ARMOR_CONFIG.kastenbrust.chestplateDurability, 0 }, new Integer[] { ARMOR_CONFIG.kastenbrust.bootsDefense, ARMOR_CONFIG.kastenbrust.leggingsDefense, ARMOR_CONFIG.kastenbrust.chestplateDefense, 0 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.kastenbrust.enabled, false, "c:ingots/steel");

	public static final ArmorType GRAND_BASCINET = new ArmorType(ARMOR_MATERIALS, ResourceLocation.fromNamespaceAndPath("magistuarmory", "grand_bascinet"), ResourceLocation.parse("magistuarmory:grand_bascinet"), ARMOR_CONFIG.grandBascinet.toughness, 0.5f, new Integer[] { 0, 0, 0, ARMOR_CONFIG.grandBascinet.helmetDurability }, new Integer[] { 0, 0, 0, ARMOR_CONFIG.grandBascinet.helmetDefense }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.grandBascinet.enabled, false, "c:ingots/steel");

	public static final ArmorType LAMELLAR = new ArmorType(ARMOR_MATERIALS, ResourceLocation.fromNamespaceAndPath("magistuarmory", "lamellar"), ResourceLocation.withDefaultNamespace("default"), ARMOR_CONFIG.lamellar.toughness, 0.0f, new Integer[] { ARMOR_CONFIG.lamellar.bootsDurability, 0, ARMOR_CONFIG.lamellar.chestplateDurability, 0 }, new Integer[] { ARMOR_CONFIG.lamellar.bootsDefense, 0, ARMOR_CONFIG.lamellar.chestplateDefense, 0 }, 9, SoundEvents.ARMOR_EQUIP_CHAIN, ARMOR_CONFIG.lamellar.enabled, false, "c:ingots/steel");

	public static void init() {
		ARMOR_MATERIALS.register();
	}
}
